import { Drawer, Toolbar } from "@mui/material";
import { Box } from "@mui/system";
import Head from "next/head";
import Image from "next/image";
import BarraLateral from "../components/BarraLateral";
import BarraSuperior from "../components/BarraSuperior";
import Card from "../components/Card";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <BarraSuperior />
      <BarraLateral />
      <Box
        component="main"
        sx={{
          flexGrow: 1,
          bgcolor: "background.default",
          margin: "120px 58px",
          flexWrap: "wrap",
          display: "flex",
        }}
      >
      <Card />
      <Card />
      <Card />
      <Card />
      <Card />
      <Card />
      <Card />
      <Card />
      <Card />
      <Card />
      </Box>
    </div>
  );
}
